config/routes.rb
Rails.application.routes.draw do

  get '/tasks', to: "tasks#index"
  get '/tasks/new', to: "tasks#new"
  get '/tasks/:id', to: "tasks#show", as: 'task'
  post '/tasks', to: "tasks#create"
  get '/tasks/:id/edit', to: "tasks#edit", as: 'edit_task'
  patch '/tasks/:id', to: "tasks#update"
  delete '/tasks/:id', to: "tasks#destroy", as: 'delete_task'

  root to: "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save(task_params)
    redirect_to task_path (@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path (@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:content, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :content %>
  <%= t.text_field :content %>
  <select>
  <%= t.label :done %>
  <option value=false selected>Undone</option>
  <option value=true>Done</option>
  </select>
  <%= t.submit %>
<% end %>

app/views/tasks/index.html.erb
<!-- criar links to delete, update, show -->
<% @tasks.each do |task| %>
  <%= link_to task.id, task_path(task) %>
  <h2><%= task.content %></h2>
  <h2><%= task.done %></h2>
  <button> <%= link_to 'EDIT', edit_task_path(task)  %> </button>
  <button> <%= link_to 'DELETE', delete_task_path(task),  method: :delete %> </button>

<% end %>

<button> <%= link_to 'NEW', tasks_new_path  %> </button>

app/views/tasks/new.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :content %>
  <%= t.text_field :content %>
  <%= t.label :done %>
  <%= t.text_field :done %>
  <%= t.submit %>
<% end %>





<!-- <form action="/tasks" method="post">
  <label for="content">Content: </label>
  <input type="text" name="task[content]" id="content">

  <label for="done?">Done? </label>
  <input type="boolean" name="task[done]" id="done">

  <input type="submit">
</form>
 -->

app/views/tasks/show.html.erb
<h2><%= @task.id %></h2>
<H3> TASK DESCRIPTION </H3>
<p><%= @task.content %></p>
<H3> Status </H3>
<p><%= @task.done %></p>
<button> <%= link_to 'BACK', tasks_path  %> </button>

<button> <%= link_to 'EDIT', edit_task_path(@task)  %> </button>

<button> <%= link_to 'DELETE', delete_task_path(@task),  method: :delete %> </button>